AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NestedStackSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      VpcId: vpc-06e96e24757e3bd24
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
Outputs:
  SecurityGroupId:
    Description: The Security Group ID
    Value: !Ref NestedStackSecurityGroup
